FROM node:current-alpine3.13

# set the working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./

COPY package-lock.json ./

RUN npm install --loglevel verbose

# add app
COPY . ./

# start app
CMD ["npm", "start"]